# --- Configuración General ---
pid_file /run/mosquitto/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/

# --- Logs ---
log_dest file /var/log/mosquitto/mosquitto.log

# --- Sin puerto seguro (TLS) ---
listener 1883 0.0.0.0
protocol mqtt

listener 8083 0.0.0.0
protocol websockets

password_file /etc/mosquitto/passwd_test.txt
allow_anonymous false


# --- Inclusiones adicionales (siempre al final) ---
include_dir /etc/mosquitto/conf.d